### ISSUE TITLE
@ExclusionPolicy("all") is not respected by the parent classes

### ISSUE THREAD

**Issue by ruimarinho** [schmittjoh/JMSSerializerBundle#100]
I'm using the agnostic storage pattern for a bundle and I have three User classes:

```
Vendor\Bundle\AuthenticationBundle\Model\User
|- Vendor\Bundle\AuthenticationBundle\Entity\User
  |- Project\AuthenticationBundle\Entity\User
```

When using the `@ExclusionPolicy("all")` on the `Project\AuthenticationBundle\Entity\User` one would expect all properties of the parents to be also excluded. However, this is not the case and requires me to add the same exclusion policy on each parent, otherwise all the parent properties are serialized. This is a problem because I don't want to create a dependency like this for the bundles.

The problem seems to lie in the way `AnnotationDriver` lists the class properties, since it doesn't take into account the parent class annotations, if set.

Is there a workaround for this?

**Comment by timwhite** [comment]
I find this confusing as well. I override properties from the parent, and have a default policy of exclude all. I even tried an explicit exclusion on the overriden property, and it's still exposed.

For example, I'm using the FOSUserBundle, and my extended user object is exposing groups, even though I have an annotation telling it to exclude it. It also means that password hashes are exposed because the ExclusionPolicy only applies to the child class.

Ideally a modification to ExclusionPolicy that allows excluding including parent would be ideal

**Comment by johnpancoast** [comment]
@schmittjoh it seems people have brought up compelling reasons to add this feature.

1.) We don't always have control over extended classes.
2.) Even when we do have control over extended classes, it's time consuming to add an exclusion policy on *N* number of extended classes.
3.) **It's a potential security issue!**. Let's say I'm serializing `A` and A extends *N* number of parents and I add the exclusion policy for all parents. If someone later comes and refactors the parents, there's easily a potential to miss the exclusions thus exposing potentially secure data when children are serialized.

Is this library still being maintained? Would you accept a PR?

**Comment by goetas** [comment]
@johnpancoast 

> Is this library still being maintained?

yes https://github.com/schmittjoh/serializer/graphs/contributors

>  Would you accept a PR?

yes, only if it solves properly the problem (how to achieve this is not yet clear), it is backward compatible and has proper tests.

Regarding the "how", I do not have any brilliant idea to do it. Some ideas: 

- Applying  `@ExclusionPolicy("all")` on the parent is a BC break.
- another solution might be  `@ExclusionPolicy("all", exludeFromParents={prop1, prop2,prop3}, includeFromParents={prop1, prop2,prop3})`
- allow `@Exclude` and `@Expose` at class level with a parameter, as example: `@Exclude("useranme")`
- just use YAML or XML metadata definition
- other?

**Comment by mvrhov** [comment]
There was a talk about validation inheritance in symfony a few weeks ago. Amongs my suggestions the one below had most sense.
However this one won't be BC. 
Applying it to serialization the behavior would be. If at least one is specified at the child level all needed have to be specified if none is specified than what n the parent is used.

**Comment by goetas** [comment]
@mvrhov can you make an example? did not get it

**Comment by mvrhov** [comment]
If at least one serialization setting is written for the child this would mean that you need to repeat all from a parent that you need. If you don't define any, then the ones from the parent are used.

**Comment by goetas** [comment]
>  repeat all from a parent that you need

Do you mean that you have to re-declare properties from parent classes?

**Comment by mvrhov** [comment]
Yes.

**Comment by goetas** [comment]
not the best option, with my proposal is not necessary

**Comment by johnpancoast** [comment]
Hi @goetas. Thanks for quick reply.

> Applying @ExclusionPolicy("all") on the parent is a BC break.

Not sure what mean. Did you mean to make the exclusion apply to all inherited classes like people in this issue brought up? That would definitely be a BC break like you said, I just don't know if that's what you meant.

> another solution might be @ExclusionPolicy("all", exludeFromParents={prop1, prop2,prop3}, includeFromParents={prop1, prop2,prop3})

> allow @Exclude and @Expose at class level with a parameter, as example: @Exclude("useranme")

I like the `include` idea if it's possible to exclude everything, including inherited properties.

The issue is that there's no way to exclude all props - local or inherited - then whitelist the values to be serialized. Blacklisting values only goes so far as the values you know at the time you made the policy. Someone can add a property later that the child isn't aware of so whitelisting is ideal IMO.

> just use YAML or XML metadata definition

This works for the cases where you know what's being inherited and you know that won't change. That's not always the case.

> Regarding the "how", I do not have any brilliant idea to do it...

Me neither! I'll try to dig in when I have some time. I just didn't see activity on this but I obviously wasn't looking in the right places. Thanks!

**Comment by jcornide** [comment]
Hi @goetas , I have exactly the same problem with the FOS User bundle as described by @timwhite , I'm not sure what you mean by 

>     just use YAML or XML metadata definition

I use YAML instead of annotations but I still can not exclude parent properties, here's my yaml for 
user:
```
  properties:
    username:
      exclude: true
    usernameCannonical:
      exclude: true
    password:
      exclude: true
    emailCanonical:
      exclude: true
    skills:
      exclude: true
    languages:
      exclude: true
    subordinates:
      exclude: true
```
skills, subordinates and languages get properly excluded but not password of emailCanonical.

I added those properties to my User entity, but even that way they're still exposed

**Comment by Preclowski** [comment]
I can just confirm its really painful issue. Even if I add exclusion_policy: ALL and exclude: true in yml mapping for inherited property, serializer don't respect those.

**Comment by goetas** [comment]
im not familiar with fos user bundle. if somebody is able to provide a failing test case, will do my best to fix it.

**Comment by Preclowski** [comment]
In my case its just simple inherited class (InvoiceAddress extends Address)

**Comment by goetas** [comment]
All the cases explained here are more or less simple... but all of them are different and failing maybe for small differences... if you can provide a minimal failing  example, possibly as PR, would be great

**Comment by Preclowski** [comment]
It would be much easier for me to give you example here.
`<?php

class Address
{
    private $firstName;
    private $lastName;
}`

`<?php

class InvoiceAddress extends Address
{
    private $taxNumber;
}`

yml mapping
`InvoiceAddress:
  exclusion_policy: ALL
  properties:
    firstName:
      exclude: true
    lastName:
      exclude: true
    taxNumber:
      expose: true
`
Result of serialization would be like

`{
  first_name: John,
  last_name: Smith,
  tax_number: 123456
}`

but expected behavior was to only show taxNumber.

**Comment by mvrhov** [comment]
Wrong expectation. The mapping is inherited. AFAIK this is documented. You should use groups for what you want to achieve.

**Comment by Preclowski** [comment]
IMO it should inherit default exclusions. Using serialization groups is a great feature, but inheritance should be optional.

And actually mapping isnt inherited (or I miss something). If I create mapping for inherited class (Address in this case) it wont be respected.

**Comment by mvrhov** [comment]
Everything you write in a xxx.yml or xxx.xml is per class and it applies only on properties of that specific class.

**Comment by goetas** [comment]
@Preclowski you need `Address.yml`

```yml
Address:
  properties:
    firstName:
      exclude: true
    lastName:
      exclude: true
```

As @mvrhov said, metadata are per class.

**Comment by goetas** [comment]
I went a bit deeper in the issue. 
This can be defined as unexpected behaviour and probably should be documented a bit better, but as @mvrhov said:

> Everything you write in a xxx.yml or xxx.xml is per class and it applies only on properties of that specific class.

This meas that if you want to influence the mapping for class, you have to define mapping information explicitly for that class (in YAML or XML).

**Comment by yapro** [comment]
```
        $serializer = SerializerBuilder::create()
            ->setSerializationContextFactory(function () {
                return \JMS\Serializer\SerializationContext::create()
                    ->setSerializeNull(true)
                    ;
            })
            ->setDeserializationContextFactory(function () {
                return \JMS\Serializer\DeserializationContext::create()
                    ->setSerializeNull(true)
                    ;
            })
            ->setAnnotationReader($annotationReader)
            ->setPropertyNamingStrategy(new SerializedNameImportantThanPropertyNameStrategy())
            ->build();
```
Ignoring some parent classes: CComponent, CModel, CActiveRecord
```
        $class = new \ReflectionClass($serializer);
        $property = $class->getProperty('navigator');
        $property->setAccessible(true);
        $navigator = $property->getValue($serializer);

        $class = new \ReflectionClass($navigator);
        $property = $class->getProperty('metadataFactory');
        $property->setAccessible(true);
        $metadataFactory = $property->getValue($navigator);

        $class = new \ReflectionClass($metadataFactory);
        $property = $class->getProperty('loadedClassMetadata');
        $property->setAccessible(true);
        $property->setValue($metadataFactory, [
            'CComponent' => new NullMetadata(new \stdClass()),
            'CModel' => new NullMetadata(new \stdClass()),
            'CActiveRecord' => new NullMetadata(new \stdClass()),
        ]);
```

**Comment by goetas** [comment]
Better to use YAML or XML metdata for the CComponent CModel CActiveRecord classes intead of doing this with the builder

**Comment by yapro** [comment]
@goetas can you provide a link to the documentation page or to an example page?
