### ISSUE TITLE
Serializing a stdClass

### ISSUE THREAD

**Issue by simshaun** [schmittjoh/JMSSerializerBundle#158]
Somebody in IRC mentioned this, so figured I'd try it out too.

It seems the bundle doesn't serialize a stdClass. Is there a reason why? (I'm clueless as to the inner workings of JMSSerializer)

```
$object = new \stdClass();
$object->foo = 'foo';
$object->bar = 'bar';
echo $serializer->serialize($object, 'json');
```

**Comment by alexdesignworks** [comment]
https://github.com/schmittjoh/serializer/pull/429

**Comment by alexdesignworks** [comment]
@lsmith77 
Casting stdClass to array converts empty objects to empty arrays. so, no good

**Comment by thomask** [comment]
I agree.

Imo:
`````
$aObj = new \StdClass();
$aObj->foo = "bar";
$aObj->fus = ["roo" => "da"];

$bObj = new \StdClass();

$arr = [
    [
       "bar" => "a",
       "obj" => $aObj,
    ],
    [
       "bar" => "a",
       "obj" => $bObj,
    ],
]
````

Should result in:

`````
[
  {
    "bar": "a",
    "obj": {
       "foo": "bar",
       "fus": {
         "roo": "da"
       } 
    }
  },
  {
   "bar": "b",
   "obj": {}
  }
]
`````

This is not possible at the moment as far as I can see

**Comment by skonsoft** [comment]
In 2016, i continue having this issue

**Comment by fracz** [comment]
2017 and still banging our heads against a brick wall.

**Comment by goetas** [comment]
@fracz 

commented about it already [here](https://github.com/schmittjoh/serializer/pull/429#issuecomment-238508002)

As already said, stdclass is an php particularity and different developers handle data inside it in different ways and because of it, there is no "true" way to solve the problem.

Even phpitself handles it in a particular way and having edge cases that was necessary to document
http://php.net/manual/en/language.types.object.php#language.types.object.casting
>  An array converts to an object with properties named by keys and corresponding values, with the exception of numeric keys which will be inaccessible unless iterated.

I understand that there are more than 5-10 issues about `stdClss`, but IMO the solution is simple:
> - get rid of stdClass in your code
> - implement this class handler in a user package

A custom handler as suggested in https://github.com/schmittjoh/serializer/pull/429 can be a solution for you, since you can decide the solution to adopt that fits in a better way your application.


In case I'm missing some important details, or you do not agree with my explanation can you explain your usecase?

**Comment by studio3w** [comment]
@goetas Thanks, I got rid of stdClass in my code and I deal with a simple array instead.
