### ISSUE TITLE
Return an array instead of object

### ISSUE THREAD

**Issue by theofidry** [schmittjoh/JMSSerializerBundle#439]
If I serialise an array, it returns a JSON array. The expected default behaviour would be to return a JSON object. If it's not intuitive, this help to prevent JSON hijacking, cf. [OWASP AJAX security guidelines](https://www.owasp.org/index.php/OWASP_AJAX_Security_Guidelines#Always_return_JSON_with_an_Object_on_the_outside).

**Comment by goetas** [comment]
Hi @theofidry :) sorry for the long feedback loop

This is a "contex" specific behavior. I mean, it is true if the client is a browser, but does not apply if the client is a guzzle client as example.
Since JMS serializer is a generic library, serializing arrays will always be serialized as arrays.

WEB specific libraries as FOSREST might convert the arrays into wraped objects, but this is not the serializer task
