### ISSUE TITLE
Serialize entity with Router dependency

### ISSUE THREAD

**Issue by cve** [schmittjoh/JMSSerializerBundle#458]
Hi,

I need to serialize Article entity which should have self link, so I need a router service as dependnecy for virtual property, how can I do that?

**Comment by rodrigorigotti** [comment]
First of all, create an attribute on your `Article` entity which will receive the link, and add both setter and getter:

    class Article {
        private $selfLink;
        public function setSelfLink($selfLink) { $this->selfLink = $selfLink; return $this; }
        public function getSelfLink() { return $this->selfLink; }
    }

Then create a `ArticleSubscriber` class which implements the `JMS\Serializer\EventDispatcher\EventSubscriberInterface` interface.

Then create a service with this article, and inject the `router` service into it:

    app.event_listener.article_subscriber:
        class: AppBundle\EventListener\ArticleSubscriber
        arguments: [ @router ]
        tags: 
            - { name: jms_serializer.event_subscriber, event: serializer.pre_serialize, method: onPreSerialize }

You will receive an `Symfony\Bundle\FrameworkBundle\Routing\Router` object as the first constructor's argument.

Then, on your subscriber's `onPreSerialize` method, which receives an object of type `JMS\Serializer\EventDispatcher\PreSerializeEvent`, do the following:

    if ($event->getObject() instanceof \AppBundle\Entity\Article) {
        $article = $event->getObject();
        $selfLink = $this->router->generate('get_article', $article->getId());
        $article->setSelfLink($selfLink);
    }

In order to have your article's self link attribute exposed, just expose it with `@Expose` annotation and serializer groups, if any.

**Comment by goetas** [comment]
see http://stackoverflow.com/questions/41548030/complex-serialization/41552643#41552643 
this is the suggested approach when serializing entities with external depencencies
