### ISSUE TITLE
Force uppermost level of output json as object

### ISSUE THREAD

**Issue by NikitaKharkov** [schmittjoh/JMSSerializerBundle#555]
So my problem is to set force all outputs as objects like next example:
```
{ <-- always 
  [
      // some data
  ]
} <-- always
```

Can you advice me how to do that? I deep into the core, I read many issues about this and all tell about back problem "How to convert object to array".
I think it could be done by setting root, but I don't understand how can I global to do that...

I use FOSRestBundle with jms annotations.

**Comment by goetas** [comment]
addressed in https://github.com/schmittjoh/serializer/pull/728

**Comment by NikitaKharkov** [comment]
Can I implement this for now or I have to wait for new realise? And if I could can give little tutorial how to make this in global state? Thanks.

**Comment by goetas** [comment]
you can try the PR, but since is still in work progress, it might change.

> And if I could can give little tutorial how to make this in global state?

i'm not sure what you mean as "global state". data are serialized depending on how you configure them.

If you want something as:

```json
{  
  prop: [
      // some data
  ]
} 
``` 
you can use a wrapper object for all your responses.

but 
```
{ <-- always 
  [
      // some data
  ]
} <-- always
```

syntactically is not correct, you need to have some property (`prop` from the previous example) to have it at least statically correct

**Comment by NikitaKharkov** [comment]
Newbie mistake of understanding json format... Sorry. Many thanks for quick answer!
