### ISSUE TITLE
What are the 2.0 options default values changes about?

### ISSUE THREAD

**Issue by lbayerl** [schmittjoh/JMSSerializerBundle#578]
In the UPGRADE for 1.x to 2.0 there is this section

> The options subscribers.doctrine_proxy.initialize_virtual_types, subscribers.doctrine_proxy.initialize_excluded and handlers.array_collection.initialize_excluded now as default are false

Unfortunately I wasn't able to find a ticket or any further information regarding these config values.

To mention them in the UPGRADE doc can only mean that these values have been 'true' before.

So can some elaborate what exactly these config values are steering and how some example app might behave differently? Any small hint might be helpful.

**Comment by goetas** [comment]
Hi 

> subscribers.doctrine_proxy.initialize_excluded
> handlers.array_collection.initialize_excluded

introduced as option with https://github.com/schmittjoh/serializer/pull/760  allows to not initialize doctrine proxies and collection if they will be excluded by same exclusion strategy. 
the feature is optional because users might have implemented some "non standard"  exclusion strategy that might result as a false positive. currently there have not been reported any of them


> subscribers.doctrine_proxy.initialize_virtual_types


implemented with https://github.com/schmittjoh/serializer/pull/684 this feature does not initialize doctrine proxies if there are custom handlers registered from them. Has been introduced as option because some developers might have built custom handlers relying on the fact that proxies are initialized. now they are not


This options have been introduced to improve the performance of the serializer, in some setups i saw 50% less doctrine queries, having the same result and no code changes.
