### ISSUE TITLE
readOnly annotation with groups

### ISSUE THREAD

**Issue by aoudjehih** [schmittjoh/JMSSerializerBundle#628]
Hello,
How can I apply readOnly annotation with condition or groups like this:

``` php
 /**
  * @JMS\ReadOnly(Groups("update"))
  */
  protected $email;
```
The aim is to disable updating email, but allow to set it in registration for example

**Comment by goetas** [comment]
Unfortunately that feature is not available..
PR are welcome

On 12 Dec 2017 00:51, "Anis Oudjehih" <notifications@github.com> wrote:

Hello,
How can I apply readOnly annotation with condition or groups like this:

`
/**

   - @jms <https://github.com/jms>\ReadOnly(Groups("update")
   */
   protected $email;
   `
   The aim is to disable updating email, but allow to set it in
   registration for example

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/schmittjoh/JMSSerializerBundle/issues/628>, or mute the
thread

**Comment by goetas** [comment]
I guess you can achieve something similar exposing that field and only when serializing and not when deciding serializing 

See https://github.com/schmittjoh/JMSSerializerBundle/issues/619#issuecomment-347926659
