### ISSUE TITLE
Optimization Doctrine to JSON

### ISSUE THREAD

**Issue by Repti31** [schmittjoh/JMSSerializerBundle#681]
Hello,

I have a performance problem with my doctrine entities.
I have an entity with 2 bi-directional ManyToMany relationships and 3 OneToMany relationship.
I tried to add 5000 of my entities, the serialization takes me 18s on a "findAll" in dev mode.

Is there an opportunity to improve this or am I required to make custom doctrine queries without object attachment ?
It makes me a little bit because I have my groups that are well done thanks to jms.

**Comment by goetas** [comment]
it is really hard to help you, performance improvements are specific you your use case... 

I can suggest to pre-fetch somehow the doctrine entities you need avoiding multiple queries... (attention to not make some of the mistakes explained in http://ocramius.github.io/blog/doctrine-orm-optimization-hydration/ by fetching too much stuff).
Can also suggest to revisit your application as fetching 5000 entities in a singe API-call/page view does not sound good anyway.


Closing since this is more of a doctrine question rather than jms/serializer.
