### ISSUE TITLE
[security issues][v3.7.0] Implicitly updating the logged in user.

### ISSUE THREAD

**Issue by presscot** [schmittjoh/JMSSerializerBundle#811]
In version 3.7 If the deserialized object is of the same type as the logged user, and if it has the same ID then both objects remain joined. It is unacceptable to be able to update a user without validation. Also objects that do not have a id in one-to-one relation cause errors.

**Comment by goetas** [comment]
Thanks for reporting this issue, but is not responsibility of this library to check which is the target object of the serialization/deserialization process. This is responsibility of your application. You can perform validation after the deserialization on your own with the rules that fit better your application.

**Comment by presscot** [comment]
@goetas The problem is that JMSSerializerBundle changes my user object called in the controller with getUser (). In controller, SensioParamConverter passes the User object to update and in case the object contains an id then, the object in the method argument is the same instance as the getUser! Helped downgrade to 3.6 version of yours bundle.

ps sorry for my English.

**Comment by goetas** [comment]
There has been really nothing in 3.7 that should impact that.(https://github.com/schmittjoh/JMSSerializerBundle/compare/3.6.0...3.7.0 has only one valuable commit). If you are able to create a reproducer repo, whould be happy to investigate more.

One note, if you are using SensioParamConverter and the param name is "user", this conflicts with the "user" variable in the session for the currently logged-in user. This is because both SensioParamConverter and the underlying security bundle save a variable named "user" in the request attribute bag.

Here an example:

```
/**
 * @ParamConverter("something", class=User)
* @Security("is_granted('view', user)")
*/ 
function getOne(User $something)
```
In this snippet we check if the currently logged in user has a permission `view`.

```
/**
 * @ParamConverter("user", class=User)
* @Security("is_granted('view', user)")
*/ 
function getOne(User $user)
```
In this snippet we check if the user being shown  has a permission `view`. This happens because ParamConverter replace the symfony default user variable with the one in the parameter
