### ISSUE TITLE
Symfony 6.4 has  a dependency on a non-existent service "annotation_reader"

### ISSUE THREAD

**Issue by nforced** [schmittjoh/JMSSerializerBundle#943]
Hello, on fresh SF 6.4 setup after adding JMS I get 

`The service "jms_serializer.metadata.annotation_and_attributes_reader" has a dependency on a non-existent service "annotation_reader".`

Which comes from
```
framework:
    annotations: false
```

What is the solution to this? 

I've checked configuration reference and don't see any relevant options to play with.

Thanks! (:

**Comment by nforced** [comment]
I looking at this and I see few things related

```
$metadataDrivers = [
            new Reference('jms_serializer.metadata.yaml_driver'),
            new Reference('jms_serializer.metadata.xml_driver'),
            // new Reference('jms_serializer.metadata.attribute_driver'), // TODO - Re-enable this driver at a later time
            new Reference('jms_serializer.metadata.annotation_driver'),
        ];

        // enable attributes support on php 8
        if (PHP_VERSION_ID >= 80000 && class_exists(AttributeReader::class)) {
            $container->register('jms_serializer.metadata.annotation_and_attributes_reader', AttributeReader::class)
                ->setArgument(0, new Reference('annotation_reader'));

            $container->findDefinition('jms_serializer.metadata.annotation_driver')
                ->replaceArgument(0, new Reference('jms_serializer.metadata.annotation_and_attributes_reader'));
        }
```
and
```
<service id="jms_serializer.metadata.annotation_driver" class="JMS\Serializer\Metadata\Driver\AnnotationDriver" public="false">
            <argument type="service" id="annotation_reader" />
            <argument type="service" id="jms_serializer.naming_strategy" />
            <argument type="service" id="jms_serializer.type_parser" on-invalid="null" />
            <argument type="constant">NULL</argument> <!-- expression evaluator -->
        </service>
        <!-- TODO - Re-enable this driver at a later time -->
        <!-- <service id="jms_serializer.metadata.attribute_driver" class="JMS\Serializer\Metadata\Driver\AttributeDriver" public="false">
            <argument type="service" id="jms_serializer.naming_strategy" />
            <argument type="service" id="jms_serializer.type_parser" on-invalid="null" />
            <argument type="constant">NULL</argument>
        </service> -->
 ```

**Comment by scyzoryck** [comment]
Hi! 
I'm afraid current implementation requires AnnotationReader dependency. I think this dependency will be solved with: https://github.com/schmittjoh/JMSSerializerBundle/pull/933 

Best, scyzoryck.

**Comment by mbabker** [comment]
That `JMS\Serializer\Metadata\Driver\AttributeDriver\AttributeReader` class that's getting wired in to enable attributes support as well as the `JMS\Serializer\Metadata\Driver\AnnotationDriver` class both have hard requirements to provide an annotation reader.  So with the current stable release of this bundle, it is indeed impossible to turn off the framework's annotation support without using compiler passes to remove those drivers.

As pointed out, #933 does fix this by no longer using the `jms_serializer.metadata.annotation_driver` service (which needs the `JMS\Serializer\Metadata\Driver\AnnotationDriver` class and has the hardcoded annotations dependency) but instead switches to a driver that supports both annotations and attributes, with the annotation support being optional, and then #937 takes a step to further validate that the bundle can work when the Annotations package is not installed since the framework no longer provides an annotation reader service in Symfony 7.

So, the fixes are there, they just haven't shipped yet.  And I'm sure the test coverage for running both the main library and this bundle without annotations can be further improved on, but being a deep-rooted dependency, it does take some time to work through decoupling it in a way that isn't intrusive to downstream users.

**Comment by goetas** [comment]
@mbabker i know that you have worked a lot of this recently, can this be considered as solved after the recent symfony 7 compatibility release https://github.com/schmittjoh/JMSSerializerBundle/pull/937 ?

**Comment by mbabker** [comment]
Yes, the combo of #933 and #937 should fix this in full.
